### ISSUE TITLE
Extension won't install

### ISSUE THREAD

**Issue by trdunsworth** [microsoft/vscode-jupyter-powertoys#24]
I tried to install the extension through VSCode and receive a notice it can't be installed with the current version. I'm running version 1.66.2 which is current.

**Comment by greazer** [comment]
Thanks for noticing and trying so quickly! The extension requires the April Release of VS Code. Prior to that, you can run it with the latest Insiders build of VS Code.

**Comment by cxrles** [comment]
so, it is still a problem? i cant install on 1.66.2 also ...
