### ISSUE TITLE
Improving cell grouping UX

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode-jupyter-powertoys#37]
I think the cell grouping experience can definitely be improved here and think that it would benefit a lot of users! Not to make this into a spec, and understanding that this won't be "to do now", but just brainstorming here:
- Ability to create more than 2 groups
- Intuitive key bindings for grouping cells, running them, and then ungrouping them
- Would be nice to have the grouping persist via git (e.g. through metadata)
- Creating custom names for groups
- Being able to easily copy and paste a group of cells to a different notebook
- Being able to always start a notebook with a specific group (e.g. "I use similar imports all the time")

![image](https://user-images.githubusercontent.com/10833267/171939415-c9f9cd23-fc0d-424a-8617-3488f71c3ee6.png)

**Comment by DonJayamanne** [comment]
Given that we have a new way built into core for renning dependant cells, it was discussed that this feature would be deprecated in favour of whats in core.
Hence closing this issue.
