### ISSUE TITLE
[Bug] Groups do not update anymore

### ISSUE THREAD

**Issue by alkatar21** [microsoft/vscode-jupyter-powertoys#47]
Clicking the button does not cause the group to be displayed at the bottom, nor does it actually add the group to the JSON.
The group is displayed as soon as you change something in the cell or it disappears from the screen once, but not in the JSON.
Furthermore, the buttons have no effect at all on new cells, only after reloading the window they have any effect at all.

![grafik](https://user-images.githubusercontent.com/61387986/180754791-7e6842fa-f384-499f-a3a3-db02194854dd.png)

Extension Version: v0.0.5
Jupyter Extension: v2022.6.1201981810
VSCode: 1.69.2

**Comment by IanMatthewHuff** [comment]
@alkatar21 apologies for the late fix here. It looks like there was a recent update to the VS Code apis that was incorrect and the groups were not getting persisted in the metadata correctly. I'm fixing this up now.

**Comment by IanMatthewHuff** [comment]
Just pushed an update 0.0.6 that should resolve this. It also cleans up some issues with the context keys from here #50
