### ISSUE TITLE
[feature request] support editing cell tags

### ISSUE THREAD

**Issue by HowcanoeWang** [microsoft/vscode-jupyter-powertoys#48]
As this tool: https://marketplace.visualstudio.com/items?itemName=donjayamanne.jupyterpowertools

![](https://raw.githubusercontent.com/DonJayamanne/vscode-jupyterpowertools/master/images/tags.gif)

Or even give a native jupyterlab panel:

![](https://docs.readthedocs.io/en/stable/_images/jupyterlab-metadata.png)

**Comment by IanMatthewHuff** [comment]
https://marketplace.visualstudio.com/items?itemName=ms-toolsai.vscode-jupyter-cell-tags

Added via a new extension.
