### ISSUE TITLE
Make Contextual Help completely available to .py files using the Interactive Window

### ISSUE THREAD

**Issue by GitHunter0** [microsoft/vscode-jupyter-powertoys#57]
Hi folks, I'm really glad this extension is being developed since I really believe this is the most important Python issue in VScode right now, as discussed [here](https://github.com/microsoft/vscode-jupyter/issues/1307).

The [Docs View](https://marketplace.visualstudio.com/items?itemName=bierner.docs-view) extension is not a satisfying alternative because it does not display the full info for some methods/functions.

Also, it would be very helpful to be able to search the Contextual Help and to navigate to previous and next help tabs (RStudio Help pane is a very good reference). 

Thank you

**Comment by GitHunter0** [comment]
Hi @DonJayamanne , is there an update or roadmap for this feature? It is vital for Interactive Window users...

**Comment by DonJayamanne** [comment]
Thanks for the feature request, unfortunately we prioritze issues based on a number of factors and one of them being number of upvotes.
Currently this issue has received just two votes (technically 1, but two parties have expressed interest)
However we do welcome contributions to this extension as this is where we try to add new features and gauge interest in those features and optionally move them into the core jupyter extesnion.

**Comment by DonJayamanne** [comment]
Thank you for filing this feature request, given we haven't add sufficient upvotes for this issue I'm closing this as not planned.
