### ISSUE TITLE
pyodide opencv-python package not available

### ISSUE THREAD

**Issue by randomlogic78** [microsoft/vscode-jupyter-powertoys#63]
The opencv-python package available in the pyodide kernel reports not available when running the kernel from vscode.dev

from platform import python_version
print(python_version())
import cv2 as cv

3.9.5
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[24], line 7
      5 from platform import python_version
      6 print(python_version())
----> 7 import cv2 as cv

ModuleNotFoundError: No module named 'cv2'

#############################
The test file from the pyodide repo uses import cv2 as cv for importing the package. https://github.com/pyodide/pyodide/blob/main/packages/opencv-python/test_opencv_python.py

**Comment by DonJayamanne** [comment]
please could you file  the issue against the pyodide extension
This extension doesn't not own the pyodide kernel functionally , that's a different extending
