### ISSUE TITLE
Issue encountered trying to connect to jupyter kernel

### ISSUE THREAD

**Issue by annddrrea** [microsoft/vscode-jupyter-powertoys#88]
Hello! I'm trying devleop a jupyter notebook extension that works specifically with dataframes read in. As part of this project, I need to access data stored in dataframes within the notebook environment. To achieve this, I attempted to connect to the notebook's currently running kernel, following the approach demonstrated in this vscode-jupyter-powertoys project:

       const jupyterExt = vscode.extensions.getExtension('ms-toolsai.jupyter');
        if (!jupyterExt) {
          return;
        }

        await jupyterExt.activate();

        const kernelService = await jupyterExt.exports.getKernelService();
        if (!kernelService) {
          console.log("Kernel service is not available.");
          return;
        }

However, my attempts have been unsuccessful, resulting in the error message: "Please contact the Jupyter Extension to get access to the Kernel API. Publisher undefined_publisher." Insights on how to correctly establish a connection to the kernel service or alternative methods to access the kernel's capabilities would be greatly appreciated. Thank you in advance for your assistance!

**Comment by DonJayamanne** [comment]
Thank you for filing this issue and trying to use the API.

The API you are attempting to use is being deprecated.
Here's the official API with a sample https://github.com/microsoft/vscode-extension-samples/tree/main/jupyter-kernel-execution-sample

If you run into any issues or would like some help/feature requests, please do not hesitate to reach out.
Feel free to create issues here https://github.com/microsoft/vscode-jupyter
