### ISSUE TITLE
honor metadata.language when exporting a ipynb file 

### ISSUE THREAD

**Issue by huang47** [microsoft/vscode-jupyter-powertoys#96]
When exporting an ipynb file, the process employs:

```json
"metadata": {
  "vscode": {
    "languageId": "sql"
  }
}
```

instead of following the nbformat v4 standard:
```json
"metadata": {
  "language": "sql"
}
```
It seems that although this extension can identify both formats, it only exports metadata specific to VSCode. I'm not sure if this is done on purpose.

**Comment by DonJayamanne** [comment]
@huang47 Please can you share the link to the nbformat v4 standard that requires the langauge to be directly under `language`.
We are following the standard, and given the fact that `language` isn't part of the standard, we're sticking it undre the `vscode` namespace which is the right thing to do,
This ensures it doesnt' conflict with others if they were to use `language`, which isn't part of the standard.

**Comment by DonJayamanne** [comment]
For now I'm closing this isssue, however if you can provide the details requested above I'm happy to reopen this issue, or feel free to createa new issue with the above information.
